# Generated by Django 4.2 on 2023-04-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_ourworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
    ]
