# Generated by Django 4.2 on 2023-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_ourworks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(unique=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(unique=True, verbose_name='Время начала'),
        ),
    ]
