# Generated by Django 4.2 on 2023-04-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_workinghours_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'default_permissions': ('change', 'view'), 'verbose_name': 'Время работы', 'verbose_name_plural': 'Время работы'},
        ),
    ]
